### ISSUE TITLE
[BiggerStreamPreview] Context menu crash (chat / member list)

### ISSUE THREAD

**Issue by jinai** [jaimeadf/BetterDiscordPlugins#244]
Right clicking anyone in chat or in member list makes Discord crash, see logs:

```
================= Starting Debug Log (2022-01-26 09:39:43.292) =================
[2022-01-26 09:39:43.293][CONSOLE:LOG] [BetterDiscord] [Startup] Loading Plugins
[2022-01-26 09:39:43.320][CONSOLE:LOG] [BDFDB] (v2.0.7) Loading Library
[2022-01-26 09:39:43.634][CONSOLE:INFO] [BiggerStreamPreview] version 1.0.10 has started.
[2022-01-26 09:39:43.769][CONSOLE:LOG] [BetterDiscord] [PluginManager] Starting to watch plugin addons.
[2022-01-26 09:39:43.770][CONSOLE:LOG] [BetterDiscord] [Startup] Loading Themes
[2022-01-26 09:39:43.774][CONSOLE:LOG] [BetterDiscord] [ThemeManager] Starting to watch theme addons.
[2022-01-26 09:39:43.774][CONSOLE:LOG] [BetterDiscord] [Startup] Removing Loading Icon
[2022-01-26 09:39:43.775][CONSOLE:LOG] [BetterDiscord] [Startup] Collecting Startup Errors
[2022-01-26 09:39:47.112][CONSOLE:LOG] [BDFDB] (v2.0.7) Finished loading Library
[2022-01-26 09:40:01.881][CONSOLE:WARN] [ComponentDispatchUtils] ComponentDispatch.subscribe: Attempting to add a duplicate listener POPOUT_CLOSE
[2022-01-26 09:40:03.247][CONSOLE:LOG] [discord_protos.discord_users.v1.FrecencyUserSettings] Loading proto
[2022-01-26 09:40:03.542][CONSOLE:ERROR] [Discord] Fatal Error: originalMethod of default in Menu TypeError: Cannot read property 'navId' of undefined
[2022-01-26 09:40:03.570][CONSOLE:ERROR] {} Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at vu (https://discord.com/assets/c0e4a59004d14946bf6f.js:5365:351)
    at Mo (https://discord.com/assets/c0e4a59004d14946bf6f.js:5333:915)
    at https://discord.com/assets/c0e4a59004d14946bf6f.js:3529:326
    at Wu (https://discord.com/assets/c0e4a59004d14946bf6f.js:5377:581)
    at t.unstable_runWithPriority (https://discord.com/assets/c0e4a59004d14946bf6f.js:5493:507)
    at Ki (https://discord.com/assets/c0e4a59004d14946bf6f.js:5313:117)
    at Hu (https://discord.com/assets/c0e4a59004d14946bf6f.js:5377:44)
    at yu (https://discord.com/assets/c0e4a59004d14946bf6f.js:5368:66)
    at https://discord.com/assets/c0e4a59004d14946bf6f.js:5313:340
    at t.unstable_runWithPriority (https://discord.com/assets/c0e4a59004d14946bf6f.js:5493:507)
    at Ki (https://discord.com/assets/c0e4a59004d14946bf6f.js:5313:117)
    at qi (https://discord.com/assets/c0e4a59004d14946bf6f.js:5313:285)
    at Xi (https://discord.com/assets/c0e4a59004d14946bf6f.js:5313:220)
    at vu (https://discord.com/assets/c0e4a59004d14946bf6f.js:5365:510)
    at Object.enqueueSetState (https://discord.com/assets/c0e4a59004d14946bf6f.js:5317:240)
    at t.h.setState (https://discord.com/assets/c0e4a59004d14946bf6f.js:5472:297)
    at https://discord.com/assets/c0e4a59004d14946bf6f.js:723:103
```

**Comment by jaimeadf** [comment]
It's the same problem as #237, and I still can't replicate it. Does that happen in all your discord servers?

**Comment by jinai** [comment]
Looks like it only happens in one particular server and not the others.

**Comment by jaimeadf** [comment]
If it's okay for you, could you send me an invite to one of those servers?

**Comment by jinai** [comment]
Sent you an invite by mail.
