### ISSUE TITLE
WhoReacted error cannot be compiled

### ISSUE THREAD

**Issue by MasamuneDate99** [jaimeadf/BetterDiscordPlugins#365]
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:166:124)
    at buildPlugin (betterdiscord://plugins/WhoReacted.plugin.js:434:12)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:441:7)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at FSWatcher.<anonymous> (<anonymous>:4:7059)

![image](https://user-images.githubusercontent.com/24244933/192470237-d897c50e-d75a-4835-bdb7-c063d37717a7.png)

**Comment by jaimeadf** [comment]
It's finally fixed. Here's the [download link](https://git-link.vercel.app/api/download?url=https://github.com/jaimeadf/BetterDiscordPlugins/blob/build/WhoReacted/dist/WhoReacted.plugin.js).
