### ISSUE TITLE
guildprofile broken

### ISSUE THREAD

**Issue by aqtsalt** [jaimeadf/BetterDiscordPlugins#367]
```TypeError: Cannot destructure property 'ModalCloseButton' of 'external_BoundedLibrary_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/GuildProfile.plugin.js:305:5)
    at eval (betterdiscord://plugins/GuildProfile.plugin.js:1877:3)
    at buildPlugin (betterdiscord://plugins/GuildProfile.plugin.js:1880:12)
    at eval (betterdiscord://plugins/GuildProfile.plugin.js:1887:7)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)```

**Comment by aqtsalt** [comment]
update?

**Comment by othello777** [comment]
This is still broken for me with the latest guildprofile. this is so sad gamers

**Comment by jack652** [comment]
i love this plugin, hope it gets fixed one day

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by KaKi87** [comment]
I guess this project is dead.

**Comment by Visne** [comment]
![image](https://user-images.githubusercontent.com/39844191/233509390-91bd304a-b29a-4e9e-b478-71bd556b19f7.png)

**Comment by Infinitay** [comment]
It's been a few months now any updates or did he decided against refactoring it?

**Comment by Chrysanthemum536** [comment]
I found a new plugin https://vencord.dev/download/ that has an option of showing server info in a popup

**Comment by KaKi87** [comment]
Personally I moved to [ServerDetails](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerDetails/).

**Comment by jack652** [comment]
> ![image](https://user-images.githubusercontent.com/39844191/233509390-91bd304a-b29a-4e9e-b478-71bd556b19f7.png)

so did he ever get down to it ?

**Comment by jack652** [comment]
> Personally I moved to [ServerDetails](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerDetails/).

unfortunately does not show you as much info as guildprofile did
