### ISSUE TITLE
SecretRingTone throwing exception on launch

### ISSUE THREAD

**Issue by lyratcm** [jaimeadf/BetterDiscordPlugins#379]
When booting up SecretRingTone throws this error

[CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. m => m?.j?.prototype._ensureAudio Cannot read property '_ensureAudio' of undefined
TypeError: Cannot read property '_ensureAudio' of undefined
    at eval (betterdiscord://plugins/SecretRingTone.plugin.js:101:85)
    at <anonymous>:4:49624
    at Function.getModule (<anonymous>:4:50567)
    at Object.getModule (<anonymous>:4:405689)
    at Function.getModule (betterdiscord://plugins/0PluginLibrary.plugin.js:2977:30)
    at Function.find (betterdiscord://plugins/0PluginLibrary.plugin.js:2964:52)
    at eval (betterdiscord://plugins/SecretRingTone.plugin.js:101:60)
    at buildPlugin (betterdiscord://plugins/SecretRingTone.plugin.js:129:12)
    at eval (betterdiscord://plugins/SecretRingTone.plugin.js:136:7)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)

SecretRingTone ver: 1.0.1
Core: 1.8.2

**Comment by B-Nerd** [comment]
new error
TypeError: Filters.byPrototypeFields is not a function
    at eval (betterdiscord://plugins/SecretRingTone.plugin.js:44:49)
    at eval (betterdiscord://plugins/SecretRingTone.plugin.js:72:12)
    at Zt.requireAddon (betterdiscord/betterdiscord.js:92:135)
    at Zt.loadAddon (betterdiscord/betterdiscord.js:85:846)
    at Zt.loadAddon (betterdiscord/betterdiscord.js:91:860)
    at Zt.loadAllAddons (betterdiscord/betterdiscord.js:85:3953)
    at Zt.initialize (betterdiscord/betterdiscord.js:83:22742)
    at Zt.initialize (betterdiscord/betterdiscord.js:91:484)
    at Object.startup (betterdiscord/betterdiscord.js:154:1976)
