### ISSUE TITLE
BiggerStreamPreview - Cant Compile [TypeError]

### ISSUE THREAD

**Issue by LcyDev** [jaimeadf/BetterDiscordPlugins#393]
```
TypeError: Cannot destructure property 'Dispatcher' of 'external_BoundedLibrary_namespaceObject.WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/BiggerStreamPreview.plugin.js:102:5)
    at buildPlugin (betterdiscord://plugins/BiggerStreamPreview.plugin.js:247:12)
    at eval (betterdiscord://plugins/BiggerStreamPreview.plugin.js:254:7)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
```

**Comment by SourCandy80** [comment]
@Tharki-God WE NEED YOU HELP pLEASE 😃

**Comment by Tharki-God** [comment]
Download [this] (https://github.com/jaimeadf/BetterDiscordPlugins/blob/82815643e624f93e7069f95280d4a4a94e84841d/dist/BiggerStreamPreview/BiggerStreamPreview.plugin.js)

**Comment by KaKi87** [comment]
Thanks, however this version isn't part of any branch of the repo and its update URL still points to the previous version, so how will future updates work ? Thanks
