### ISSUE TITLE
BUG guildprofile 

### ISSUE THREAD

**Issue by aqtsalt** [jaimeadf/BetterDiscordPlugins#400]
Hello I am experiencing an error with this plugin

Guildprofile can't be compiled
TypeError: Cannot destructure property 'ModalCloseButton' of 'external_BoundedLibrary_namespaceObject.WebpackModules.getByProps(...)' as it is undefined. at eval (betterdiscord://plugins/GuildProfile.plugin.js:305:5) at eval (betterdiscord://plugins/GuildProfile.plugin.js:1877:3) at buildPlugin (betterdiscord://plugins/GuildProfile.plugin.js:1880:12) at eval (betterdiscord://plugins/GuildProfile.plugin.js:1887:7) at Object.requireAddon (<anonymous>:4:43438) at Object.loadAddon (<anonymous>:4:9197) at Object.loadAddon (<anonymous>:4:41165) at Object.loadAllAddons (<anonymous>:4:11607) at Object.initialize (<anonymous>:4:6257) at Object.initialize (<anonymous>:4:40368) at Object.startup (<anonymous>:4:376262)

**Comment by MacGyverPY** [comment]
same, looks like its...forgotten

**Comment by aqtsalt** [comment]
@jaimeadf how to stop this bug?

**Comment by gmanc2** [comment]
Bump. Any update? @jaimeadf

**Comment by ilan0098** [comment]
I don't think it's forgotten , the dev literally said on his Discord server that Discord updates break his plugins and he can't figure out how to fix them
