### ISSUE TITLE
Can't load Who Reacted plug-in

### ISSUE THREAD

**Issue by Devin-G-Squire** [jaimeadf/BetterDiscordPlugins#411]
When I try to install and enable the Who Reacted plug-in I get these errors
![Screenshot 2024-05-06 at 2 08 20 PM](https://github.com/jaimeadf/BetterDiscordPlugins/assets/141097351/bbe6b845-819c-47f5-8736-b4ddbe9e4e63)

![Screenshot 2024-05-06 at 2 05 01 PM](https://github.com/jaimeadf/BetterDiscordPlugins/assets/141097351/6ab05231-3b42-4ab4-9dc1-0199cf040bbe)

TypeError: this._dispatcher.createToken is not a function
    at new E (https://discord.com/assets/35705.68d74baeb9f25c82c1d6.js:1:7474617)
    at new DefaultSettingsStore (betterdiscord://plugins/WhoReacted.plugin.js:128:9)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:165:23)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:730:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at betterdiscord/renderer.js:5:4392

**Comment by Artaherzadeh** [comment]
Same

**Comment by 0xeac7** [comment]
my pull request fixes it - https://github.com/jaimeadf/BetterDiscordPlugins/pull/412

**Comment by 0xeac7** [comment]
fixed plugin: https://gist.github.com/0xeac7/b44f7519c8edb4ba16942fcbdfae35ad

**Comment by Devin-G-Squire** [comment]
I'm able to enable it now. User icons are still not showing

**Comment by Qoolize** [comment]
It still does not work.

**Comment by WickedSquirrel** [comment]
same

**Comment by GildasEdraE** [comment]
> fixed plugin: https://gist.github.com/0xeac7/b44f7519c8edb4ba16942fcbdfae35ad

It's still doesn't

**Comment by darthxneon** [comment]
still broken, fix from @0xeac7 does not work unfortunately

**Comment by that1polish** [comment]
ecountering issues also
plz fix

**Comment by azzydoesgit** [comment]
It has been broken for me for a very long time as well

**Comment by dav1312** [comment]
Enjoy (until it breaks again!) https://gist.github.com/dav1312/928a20076baa6fa0796c269ec8978357

**Comment by darthxneon** [comment]
thx, I already moved to Vencord to have it working, and I am enjoying much better overall performance, not coming back to BD.
