### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by EclipsesDev** [jaimeadf/BetterDiscordPlugins#413]
pls fix it 
![Screenshot 2024-08-11 204843](https://github.com/user-attachments/assets/d157585d-eaa5-4bc9-918f-85f4494463e2)

**Comment by maciupikciuxd** [comment]
same problem here, adding this error appearing on discord startu(win 11 64bit):
TypeError: this._dispatcher.createToken is not a function
    at new E (https://discord.com/assets/web.84286311a93cfaa6fbea.js:12:9536713)
    at new DefaultSettingsStore (betterdiscord://plugins/WhoReacted.plugin.js:128:9)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:165:23)
    at eval (betterdiscord://plugins/WhoReacted.plugin.js:730:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by alxjspalma** [comment]
Do we have a fix ETA? @jaimeadf
